Adding all file and directory content for package
Swift-BAT/UnmaskedResponder pull request #1
Opened 2023-06-22 23:26 UTC by metalphase

2023-06-22 23:34 UTC, Tohuvavohu commented
Why do you need the following pieces

/data/bright_source_cat.fits
/data/F646018360

there may be other extraneous pieces too.

You can look at what you actually need to do the relevant response calculation and tests, and only include that.

2023-06-23 00:54 UTC, Tohuvavohu commented
also many of the requirements listed are not needed

2023-06-23 00:54 UTC, Tohuvavohu commented on src/nitrates_response/config.py
> +# email password file
Dont need this

2023-06-24 23:51 UTC, metalphase commented
@Tohuvavohu  Removed the F64601860 directory and added the test_response.py file that will run using pytest. I also edited the requirements to just include the necessary modules and just cleaned up the repository in general according to your advice

2023-06-24 23:56 UTC, Tohuvavohu requested changes
Great job, it's looking really nice!

Two things:
1) If this is set up properly, install should only require 
'pip install .' in the root directory

2) please squash your commits before first merge

2023-06-24 23:59 UTC, Tohuvavohu commented
Also, when you've figured that out, install instructions should be in README.md

2023-06-25 06:34 UTC, metalphase commented
Looks like the package should install just as you described in 1.  I've included the install instructions into the README.md file. I'm still figuring out how to squash my last commits. Should I be squashing all of my commits into a singular one after your initial commit for the repo?

2023-06-25 14:24 UTC, Tohuvavohu commented
Yep!

2023-06-25 14:33 UTC, Tohuvavohu commented
also you have an extraneous, empty, file called 'ls'

2023-06-26 23:28 UTC, metalphase commented
@Tohuvavohu alright, was a nail-biter but was able to squash the commits successfully and now all the commits show up as a singular commit.

2023-06-26 23:28 UTC, metalphase commented
Was there any other things that needed to be changed?

2023-06-26 23:51 UTC, Tohuvavohu approved these changes

2023-06-26 23:51 UTC, merged